name: CI

on:
  push:
    branches:
      - master
  pull_request_target:
    branches:
      - master

jobs:
  notify-start:
    runs-on: ubuntu-latest
    steps:
      - name: Send Initial Slack Message
        id: send_initial_slack_ci
        uses: rennf93/good-comms@master
        with:
          SLACK_WEBHOOK: '${{ secrets.SLACK_WEBHOOK }}'
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
          STATUS: 'Started'
          CHANNEL_ID: '${{ secrets.SLACK_CHANNEL }}'
          AUTHOR_NAME: 'FastAPI Guard - CI & Tests'
          AUTHOR_LINK: 'https://github.com/rennf93/fastapi-guard'
          AUTHOR_ICON: ':test_tube:'
          TITLE: 'CI & Tests Started'
          TITLE_LINK: 'https://github.com/rennf93/fastapi-guard/actions'
          MESSAGE: |
            .
            *DEPLOYMENT TRIGGERED CI & TESTS!*

            Matrix:
              Python: [ 3.10, 3.11, 3.12 ]

            Commit:
              ${{ github.event.head_commit.message }}
            .
          COLOR: warning

  test:
    runs-on: ubuntu-latest
    needs: notify-start

    permissions:
      pull-requests: write

    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12']

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r reqs.pip
          pip install -e .

      - name: Run tests
        env:
          IPINFO_TOKEN: ${{ secrets.IPINFO_TOKEN }}
        run: |
          pip install pytest
          pytest

      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 guard/
          flake8 handlers/

      - name: Format code with black
        run: |
          pip install black
          black .

  notify-result:
    runs-on: ubuntu-latest
    needs: [notify-start, test]
    if: always()
    steps:
      - name: Notify Success on Slack Channel
        if: ${{ needs.test.result == 'success' }}
        uses: rennf93/good-comms@master
        with:
          SLACK_WEBHOOK: '${{ secrets.SLACK_WEBHOOK }}'
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
          STATUS: 'Success'
          CHANNEL_ID: '${{ secrets.SLACK_CHANNEL }}'
          AUTHOR_NAME: 'FastAPI Guard - CI & Tests'
          AUTHOR_LINK: 'https://github.com/rennf93/fastapi-guard'
          AUTHOR_ICON: ':gem:'
          TITLE: 'CI & Tests Successful'
          TITLE_LINK: 'https://github.com/rennf93/fastapi-guard/actions'
          MESSAGE: |
            .
            All Python versions passed successfully!

            Commit message:
              ${{ github.event.head_commit.message }}

            Commit URL:
              ${{ github.event.head_commit.url }}
            .
          COLOR: good
          SLACK_THREAD_TS: ${{ needs.notify-start.outputs.send_initial_slack_ci.SLACK_THREAD_TS }}

      - name: Send Failure Notification to Slack
        if: ${{ needs.test.result == 'failure' }}
        uses: rennf93/good-comms@master
        with:
          SLACK_WEBHOOK: '${{ secrets.SLACK_WEBHOOK }}'
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
          STATUS: 'Failed'
          CHANNEL_ID: '${{ secrets.SLACK_CHANNEL }}'
          AUTHOR_NAME: 'FastAPI Guard - CI & Tests'
          AUTHOR_LINK: 'https://github.com/rennf93/fastapi-guard'
          AUTHOR_ICON: ':skull:'
          TITLE: 'CI & Tests Failed'
          TITLE_LINK: 'https://github.com/rennf93/fastapi-guard/actions'
          MESSAGE: |
            .
            Tests failed!

            Matrix Results:
            ${{ join(needs.test.result) }}

            Commit message:
              ${{ github.event.head_commit.message }}

            Commit URL:
              ${{ github.event.head_commit.url }}

            Please check the logs for more details.
            .
          COLOR: danger
          SLACK_THREAD_TS: ${{ needs.notify-start.outputs.send_initial_slack_ci.SLACK_THREAD_TS }}
